version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arithmetic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3320:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
