apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-backend
  labels:
    app: arithmetic-backend
spec:
  selector:
    matchLabels:
      app: arithmetic-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: "arithmetic-backend"
    spec:
      containers:
        - name: arithmetic-backend
          image: "vitor96k/arithmetic-backend:4.0.0"
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 100m
              memory: 650Mi
              
          readinessProbe: # Monitor and tag container as not ready
            httpGet:
              path: /
              port: 80 # Container Port
            periodSeconds: 3 # Frequency to monitor the container
            failureThreshold: 1 # How many times can it fail before restarting
            initialDelaySeconds: 5

          envFrom:
            - configMapRef:
                name: arithmetic-backend-staging-env
