apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-backend
  labels:
    app: arithmetic-backend
spec:
  selector:
    matchLabels:
      app: arithmetic-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: arithmetic-backend
    spec:
      containers:
        - name: arithmetic-backend
          image: "vitor96k/arithmetic-backend:5.0.4"
          volumeMounts:
            - name: logs-volume
              mountPath: /app/.logs/
              subPath: calculator/log/
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 100m
              memory: 650Mi

          envFrom:
          - secretRef:
              name: calculator-secrets
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-volume-claim