name: push-image-develop

on:
  push:
    tags:
      - "*"

jobs:
  test_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          echo "tag_name=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vitor96k/arithmetic-backend:${{ steps.vars.outputs.tag_name }}
          platforms: linux/amd64,linux/arm64

      - name: Checkout K8s Repository
        uses: actions/checkout@v3
        with:
          repository: vitoraderaldo/arithmetic-k8s
          ref: develop
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 'Install Kustomize'
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.1.0'

      - name: 'Kustomize build'
        run: |
          cd calculator/k8s
          kustomize edit set image vitor96k/arithmetic-backend:${{ steps.vars.outputs.tag_name }}

      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: 'Commit '
        run: |
          git add .
          git commit -m "Set arithmetic-backend tag to ${{ steps.vars.outputs.tag_name }}"

      - name: Push kustomization.yaml
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: develop
          repository: vitoraderaldo/arithmetic-k8s
